suspicious_patterns:
  - "Failed login from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "SQL Injection attempt detected from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "Unauthorized access from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "Multiple failed login attempts from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "Suspicious file upload from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
log_file: "mock_logs.txt"
monitor_duration: 30
firewall_api_url: "http://example.com/api/block_ip"
smtp_server: "smtp.example.com"
smtp_port: 587
smtp_user: "${SMTP_USER}"
smtp_password: "${SMTP_PASSWORD}"
alert_recipient: "admin@example.com"
slack_webhook_url: "${SLACK_WEBHOOK_URL}"

# Configuration validation
required_fields:
  - suspicious_patterns
  - log_file
  - monitor_duration
  - firewall_api_url
  - smtp_server
  - smtp_port
  - smtp_user
  - smtp_password
  - alert_recipient
  - slack_webhook_url