suspicious_patterns:
  - "Brute force attack detected from IP: (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "Failed login attempt from IP: (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "SQL Injection detected from IP: (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "Unauthorized admin access attempt from IP: (\\d+\\.\\d+\\.\\d+\\.\\d+)"
  - "Port scan detected from IP: (\\d+\\.\\d+\\.\\d+\\.\\d+)"

log_file: "attacker_logs.log"
monitor_duration: 30
firewall_api_url: "http://example.com/api/block_ip"
smtp_server: "smtp.example.com"
smtp_port: 587
smtp_user: "${SMTP_USER}"
smtp_password: "${SMTP_PASSWORD}"
alert_recipient: "admin@example.com"
slack_webhook_url: "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"
virus_total_api_key: "3dc0ce4aca4ff8a6f12214553284760607e3760c264cbee61f66da2803048181"

required_fields:
  - suspicious_patterns
  - log_file
  - monitor_duration
  - firewall_api_url
  - smtp_server
  - smtp_port
  - smtp_user
  - smtp_password
  - alert_recipient
  - slack_webhook_url
  - virus_total_api_key